---
abstract: 'a light and pure-Perl PSGI/Plack HTTP server with pre-forks'
author:
  - 'Piotr Roszatycki <dexter@cpan.org>'
  - 'Piotr Roszatycki <dexter@cpan.org>'
  - 'Jeremy Howard <j+daemonize@howard.fm>'
  - 'Paul Seamons <paul@seamons.com>'
build_requires:
  HTTP::Tiny: '0'
  Test::More: '0.88'
  Test::TCP: '0.15'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Starlight
provides:
  Plack::Handler::Starlight:
    file: lib/Plack/Handler/Starlight.pm
    version: '0.0303'
  Starlight:
    file: lib/Starlight.pm
    version: '0.0303'
  Starlight::Server:
    file: lib/Starlight/Server.pm
    version: '0.0303'
requires:
  Plack: '0.992'
  perl: '5.008001'
resources:
  bugtracker: http://github.com/dex4er/Starlight/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/dex4er/Starlight
version: '0.0303'
